service: intergov-document-api

plugins:
  - serverless-python-requirements
  - serverless-wsgi

package:
  individually: true
  include:
    - '!../../**'
    - '../../intergov/**'
  exclude:
    - '**'

custom:
  wsgi:
    app: intergov.apis.document.lambda.app
    packRequirements: false
  pythonRequirements:
    dockerizePip: 'non-linux'
    fileName: ../../intergov/requirements/prod.txt

provider:
  name: aws
  runtime: python3.6
  stage: dev
  region: ap-southeast-2

functions:
  document_api:
    handler: wsgi_handler.handler
    events:
      - http: ANY /
      - http: ANY {proxy+}
